document.getElementById("btn").addEventListener("click", () => {
  const randomNumberGenerator = Math.floor(Math.random() * quotesArray.length);
  document.querySelector("p").textContent = quotesArray[randomNumberGenerator];
});

const quotesArray = [
  "'It's never been easier to start a company. It's never been harder to build one.'",
  "'Reading is more efficient when at rest. Audio is more efficient when in motion.'",
  "'Your goal in life is to find out the people who need you the most, to find out the business that needs you the most, to find the project and the art that needs you the most. There is something out there just for you.'",
  "'Seek wealth, not money or status. Wealth is having assets that earn while you sleep. Money is how we transfer time and wealth. Status is your place in the social hierarchy.'",
  "'Founders run every sprint as if they’re about to lose, but grind out the long race knowing that victory is inevitable.'",
  "'Doctors won’t make you healthy. Nutritionists won’t make you slim. Teachers won’t make you smart. Gurus won’t make you calm. Mentors won’t make you rich.Trainers won’t make you fit. Ultimately, you have to take responsibility. Save yourself.'",
  "'It is the mark of a charlatan to explain a simple concept in a complex way'",
  "'Don’t do things that you know are morally wrong. Not because someone is watching, but because you are. Self-esteem is just the reputation that you have with yourself. You’ll always know.'",
  "'If you’re more passionate about founding a business than the business itself, you can fall into a ten year trap. Better to stay emotionally unattached and select the best opportunity that arises.'",
  "'No meetings before 11am. No meetings when emails or calls will do. Don’t schedule calls, text coordinate them on the fly when possible. Cram all meetings into two days a week. 1-on-1s are usually 30-minute walking meetings.(Meetings are the death of productivity)'",
  "'Twitter is a way to broadcast messages to hundreds of millions of people to find the few dozen that you actually want to talk to.'",
  "'Become the best in the world at what you do. Keep redefining what you do until this is true.'",
  "'Knowledge is a skyscraper. You can take a shortcut with a fragile foundation of memorization, or build slowly upon a steel frame of understanding.'",
  "'Specific knowledge is found by pursuing your genuine curiosity and passion rather than whatever is hot right now.'",
  "'People who try to look smart by pointing out obvious exceptions actually signal the opposite.'",
  "'If you eat, invest, and think according to what the ‘news’ advocates, you’ll end up nutritionally, financially and morally bankrupt.'",
  "'Success is the enemy of learning. It can deprive you of the time and the incentive to start over. Beginner’s mind also needs beginner’s time.'",
  "'To see if they really think that things are getting worse, ask them if they’d rather live in the future or in the past.'",
  "'If you can't decide, the answer is No.'",
  "'The closer you are to the truth, the more silent you become inside.'",
  "'If you’re leveraged with capital, code, or people, and own equity, then good decisions have a much larger earning impact than hard work'",
  "'Learn to sell. Learn to build. If you can do both, you will be unstoppable.'",
  "'Technology is not only the thing that moves the human race forward, but it’s the only thing that ever has. Without technology, we’re just monkeys playing in the dirt.'",
  "'People who try to look smart by pointing out obvious exceptions actually signal the opposite.'",
  "'Technology democratizes consumption but consolidates production. The best person in the world for anything, gets to do it for everyone.'",
  "'There is no skill called “business.” Avoid business magazines and business classes.'",
  "'Success is the enemy of learning. It can deprive you of the time and the incentive to start over. Beginner’s mind also needs beginner’s time.'",
  "'Yoga cultivates Peace of Body. Meditation cultivates Peace of Mind.'",
  "'Branding requires accountability. To build a great personal brand (an eponymous one), you must take on the risk of being publicly wrong.'",
  "'Correlation isn’t causation but neurons that fire together wire together. Thus the confusion.'",
  "'It's never been easier to start a company. It's never been harder to build one.'",
  "'If you’re more passionate about founding a business than the business itself, you can fall into a ten year trap. Better to stay emotionally unattached and select the best opportunity that arises.'",
  "'The two party system is an emergent bug in representative democracy.'",
  "'A busy mind accelerates the passage of subjective time.'",
  "'If you’re more passionate about founding a business than the business itself, you can fall into a ten year trap. Better to stay emotionally unattached and select the best opportunity that arises.'",
  "'Twitter is a microphone. It makes instant celebrities of each of us, with retweet fame and follower fans. Celebrities may be the unhappiest people in the world.'",
  "'Don’t do things that you know are morally wrong. Not because someone is watching, but because you are. Self-esteem is just the reputation that you have with yourself. You’ll always know.'",
  "'All the value in life, including in relationships, comes from compound interest.'",
  "'The profile picture is the logo for your Twitter brand. Pick a unique picture that's recognizable from a distance, and don't change it. It'll stand out in a pile of mentions and allow busy accounts to notice and remember you.'",
  "'Zero-sum games tend towards conflict. Positive-sum games tend towards cooperation.'",
  "'Children are happy because: 1) They're not self conscious 2) They lack a sense of time pressure 3) They've no goals. The bottom line is they are living from moment to moment, and the mind is not there to interfere in their bliss.'",
  "'The secret to public speaking is to speak as if you were alone.'",
  "'Leverage is a force multiplier for your judgement.'",
  "'If you eat, invest, and think according to what the ‘news’ advocates, you’ll end up nutritionally, financially and morally bankrupt.'",
  "'A good conference is a vacation that you take with really smart friends.'",
  "'The better the reviewed knows the reviewer, the kinder the review. Negative reviews get rarer as you go from Amazon to Yelp to AirBnB.'",
  "'True religion is rejecting all teachings and thinking for yourself.'",
  "'Notifications are just alarm clocks that someone else is setting for you.'",
  "'Whether you’re excited or nervous when your favorite asset falls in price marks whether you’re investing or merely speculating.'",
  "'An early exit for your startup is a mirage in the desert. If you thirst for it, it disappears.'",
  "'The selfish reason to be ethical is that it attracts the other ethical people in the network.'",
  "'Making money through an early lucky trade is the worst way to win. The bad habits that it reinforces will lead to a lifetime of losses.'",
  "'Self-image is the prison. Other people are the guards.'",
  "'If you can't see yourself working with someone for life, don't work with them for a day.'",
  "'Founders run every sprint as if they’re about to lose, but grind out the long race knowing that victory is inevitable.'",
  "'When building habits, choose consistency over content. The best book is the one you can’t put down. The best exercise is the one you enjoy doing every day. The best health food is the one you find tasty. The best work is the work you’d do for free.'",
  "'Pick an industry where you can play long term games with long term people.'",
  "'Wealth creation is an evolutionarily recent positive-sum game. Status is an old zero-sum game. Those attacking wealth creation are often just seeking status.'",
  "'The fundamental delusion - there is something out there that will make me happy and fulfilled forever.'",
  "'Specific knowledge is found by pursuing your genuine curiosity and passion rather than whatever is hot right now.'",
  "'A taste of freedom can make you unemployable.'",
  "'Quick relaxation hack: “Drop face, soft belly”. The face is usually wearing a mask to signal to others. The belly is often chronically tensed in a fight-or-flight response.'",
  "'Seek wealth, not money or status. Wealth is having assets that earn while you sleep. Money is how we transfer time and wealth. Status is your place in the social hierarchy.'",
  "'Founders run every sprint as if they’re about to lose, but grind out the long race knowing that victory is inevitable.'",
  "'We are biological machines programmed to survive and replicate. Happy is anti-evolution.'",
  "'School, politics, sports, and games train us to compete against others. True rewards - wealth, knowledge, love, fitness, and equanimity - come from ignoring others and improving ourselves.'",
  "'Your closest friends are the ones you can have a relationship with about nothing.'",
  "'Your goal in life is to find out the people who need you the most, to find out the business that needs you the most, to find the project and the art that needs you the most. There is something out there just for you.'",
  "'The variation between engineering output is so high that the best engineers will always be underpaid, and driven towards founding companies.'",
  "'Making money through an early lucky trade is the worst way to win. The bad habits that it reinforces will lead to a lifetime of losses.'",
  "'If you want to be successful, surround yourself with people who are more successful than you are, but if you want to be happy, surround yourself with people who are less successful than you are.'",
  "'A contrarian isn’t one who always objects - that’s a conformist of a different sort. A contrarian reasons independently, from the ground up, and resists pressure to conform.'",
  "'Twitter is online society. To survive it, the individual must ignore the news, leave the mobs, disassociate from the angry and the confused, and dismiss both compliments and insults.'",
  "'Don't write to make money, write to build relationships with like minded people that you haven't yet met.'",
  "'Success is the enemy of learning. It can deprive you of the time and the incentive to start over. Beginner’s mind also needs beginner’s time.'",
  "'We say “peace of mind” but really what we want is peace from mind.'",
  "'Changing your interpretation of your past is often just as good as changing your past.'",
  "'A contrarian isn’t one who always objects - that’s a conformist of a different sort. A contrarian reasons independently, from the ground up, and resists pressure to conform.'",
  "'Work as hard as you can. Even though who you work with and what you work on are more important than how hard you work.'",
  "'Involve groups in the creative process and you inevitably end up with a pile of pleasing, socially-acceptable lies. Contrast blockbuster movies with the great books.'",
  "'If you’re more passionate about founding a business than the business itself, you can fall into a ten year trap. Better to stay emotionally unattached and select the best opportunity that arises.'",
  "'You will get rich by giving society what it wants but does not yet know how to get. At scale.'",
  "'If friends spoke to us like politicians and actors, reading aloud scripts written by others, we wouldn't take them seriously as individuals.'",
  "'A good conference is a vacation that you take with really smart friends.'",
  "'Your goal in life is to find out the people who need you the most, to find out the business that needs you the most, to find the project and the art that needs you the most. There is something out there just for you.'",
  "'A rational person can find peace by cultivating indifference to things outside of their control.'",
  "'Building a following on Twitter is building a castle out of sand, as the implacable tide shifts in and out. Invest in the free and open web - blogs, podcasts, newsletters.'",
  "'Knowledge is either from direct experience or from verifiable, falsifiable science. There is knowledge that is transmitted but not verifiable / falsifiable, and this knowledge is indistinguishable from that which is false.'",
  "'Politics is the exercise of power without merit.'",
  "'If you’re more passionate about founding a business than the business itself, you can fall into a ten year trap. Better to stay emotionally unattached and select the best opportunity that arises.'",
  "'Creativity starts with an empty calendar and ends with a full one.'",
  "'A rational person can find peace by cultivating indifference to things outside of their control.'",
  "'We prefer to see “winners” as “naturally talented” rather than “hard working.” Because if it were reversed, what would that imply about us?'",
  "'Code, money, guns, and encryption are all becoming speech. The first amendment is the last word on freedom.'",
  "'Technology democratizes consumption but consolidates production. The best person in the world for anything, gets to do it for everyone.'",
  "'It's never been easier to start a company. It's never been harder to build one.'",
  "'Signaling virtue is a vice.'",
  "'Your goal in life is to find out the people who need you the most, to find out the business that needs you the most, to find the project and the art that needs you the most. There is something out there just for you.'",
  "'Don’t do things that you know are morally wrong. Not because someone is watching, but because you are. Self-esteem is just the reputation that you have with yourself. You’ll always know.'",
  "'Specific knowledge is found by pursuing your genuine curiosity and passion rather than whatever is hot right now.'",
  "'Read what you love until you love to read.'",
  "'The biggest cost of politics is that it can cause you to have comforting, false, and ultimately expensive beliefs about business and science.'",
  "'Twitter is a microphone. It makes instant celebrities of each of us, with retweet fame and follower fans. Celebrities may be the unhappiest people in the world.'",
  "'Technology is the application of knowledge to control the natural world. It’s the greatest driver of both human prosperity and our capacity for self-annihilation.'",
  "'When building habits, choose consistency over content. The best book is the one you can’t put down. The best exercise is the one you enjoy doing every day. The best health food is the one you find tasty. The best work is the work you’d do for free.'",
  "'A busy mind accelerates the passage of subjective time.'",
  "'The best way, perhaps the only way, to change others is to become an example.'",
  "'In an age of infinite leverage, judgement is the most important skill.'",
  "'If you’re more passionate about founding a business than the business itself, you can fall into a ten year trap. Better to stay emotionally unattached and select the best opportunity that arises.'",
  "'Judgement requires experience, but can be built faster by learning foundational skills.'",
  "'The first rule of handling conflict is don't hang around with people who are constantly engaging in conflict.'",
  "'The Efficient Markets Hypothesis fails because humans are herd animals, not independent rational actors. Thus the best investors tend to be antisocial and contrarian.'",
  "'Humans aren’t evolved to worry about everything happening outside of their immediate environment.'",
  "'The selfish reason to be ethical is that it attracts the other ethical people in the network.'",
  "'Relax. You’ll live longer *and* perform better.'",
  "'Self-image is the prison. Other people are the guards.'",
  "'Trade money for time, not time for money. You’re going to run out of time first.'",
  "'People who live far below their means enjoy a freedom that people busy upgrading their lifestyles can’t fathom.'",
  "'Don’t do things that you know are morally wrong. Not because someone is watching, but because you are. Self-esteem is just the reputation that you have with yourself. You’ll always know.'",
];
